<?php

/**
 * Public machine-discovery representation for Agent.
 *
 * The output is intentionally simple Markdown/plain text so it remains useful
 * to crawlers and agents without coupling Agent to a specific AI provider.
 *
 * @package Agent
 */

/**
 * Collapse presentation HTML into safe single-line discovery text.
 */
function AGENT_discoveryText($value)
{
    $value = html_entity_decode(strip_tags((string) $value), ENT_QUOTES, 'UTF-8');
    $value = preg_replace('/\s+/u', ' ', $value);
    return trim($value);
}

/**
 * Build public llms-style discovery text for the active Geeklog site.
 */
function AGENT_buildLlmsText()
{
    global $_CONF;

    if (!AGENT_isEnabled() || (int) AGENT_getConfig('llms_enabled', 1) !== 1) {
        return '';
    }

    $siteName = isset($_CONF['site_name']) ? AGENT_discoveryText($_CONF['site_name']) : 'Geeklog site';
    $siteUrl = isset($_CONF['site_url']) ? rtrim((string) $_CONF['site_url'], '/') : '';
    $description = AGENT_discoveryText(AGENT_getConfig('site_description', ''));
    if ($description === '' && isset($_CONF['site_slogan'])) {
        $description = AGENT_discoveryText($_CONF['site_slogan']);
    }

    $limit = (int) AGENT_getConfig('recent_limit', 10);
    if ($limit < 1) {
        $limit = 10;
    }
    $limit = min($limit, 50);

    $lines = array();
    $lines[] = '# ' . $siteName;
    $lines[] = '';
    if ($description !== '') {
        $lines[] = '> ' . $description;
        $lines[] = '';
    }

    if ($siteUrl !== '') {
        $lines[] = 'Canonical site: ' . $siteUrl . '/';
        $lines[] = '';
    }

    $lines[] = '## Public content';
    $lines[] = '';

    $hasResources = false;
    foreach (AGENT_getEnabledProviders() as $provider) {
        if (!AGENT_providerAvailable($provider)) {
            continue;
        }

        $resources = AGENT_getProviderResources(
            $provider,
            array(
                'limit' => $limit,
                'order' => 'modified-desc'
            )
        );

        if (empty($resources)) {
            continue;
        }

        $hasResources = true;
        $lines[] = '### ' . ucfirst($provider);
        $lines[] = '';
        foreach ($resources as $resource) {
            if (empty($resource['title']) || empty($resource['canonical_url'])) {
                continue;
            }

            $title = AGENT_discoveryText($resource['title']);
            $url = (string) $resource['canonical_url'];
            $excerpt = !empty($resource['excerpt']) ? AGENT_discoveryText($resource['excerpt']) : '';

            $line = '- [' . $title . '](' . $url . ')';
            if ($excerpt !== '') {
                $line .= ' — ' . $excerpt;
            }
            $lines[] = $line;
        }
        $lines[] = '';
    }

    if (!$hasResources) {
        $lines[] = 'No provider collection is currently available.';
        $lines[] = '';
    }

    if ($siteUrl !== '') {
        $lines[] = '## Site discovery';
        $lines[] = '';
        $lines[] = '- [Home](' . $siteUrl . '/)';
        $lines[] = '- [XML sitemap](' . $siteUrl . '/sitemap.xml)';
        $lines[] = '';
    }

    $lines[] = 'Generated by Geeklog Agent from the active site context and permission-aware provider contracts.';

    return implode("\n", $lines) . "\n";
}
