<?php

/**
 * Public machine-discovery representation for Agent.
 *
 * The output is intentionally simple Markdown/plain text so it remains useful
 * to crawlers and agents without coupling Agent to a specific AI provider.
 *
 * @package Agent
 */

/**
 * Collapse presentation HTML into safe single-line discovery text.
 *
 * Unexpanded Geeklog autotags are removed from discovery output. They are
 * presentation/runtime instructions rather than useful machine-readable prose.
 */
function AGENT_discoveryText($value)
{
    $value = html_entity_decode(strip_tags((string) $value), ENT_QUOTES, 'UTF-8');

    // Remove unresolved Geeklog-style autotags such as [forms:feedback].
    $value = preg_replace('/\[[A-Za-z][A-Za-z0-9_-]*:[^\]\r\n]*\]/u', ' ', $value);

    // Remove unresolved image autotags such as [image1] or [imageX].
    $value = preg_replace('/\[image(?:\d+|X)\]/iu', ' ', $value);

    $value = preg_replace('/\s+/u', ' ', $value);
    return trim($value);
}

/**
 * Return a compact discovery excerpt without cutting normal output excessively.
 */
function AGENT_discoveryExcerpt($value, $maxLength = 300)
{
    $value = AGENT_discoveryText($value);
    $maxLength = max(80, min(1000, (int) $maxLength));

    if ($value === '' || strlen($value) <= $maxLength) {
        return $value;
    }

    if (function_exists('COM_truncate')) {
        return COM_truncate($value, $maxLength, '...');
    }

    return rtrim(substr($value, 0, $maxLength - 3)) . '...';
}

/**
 * Escape text used inside a Markdown link label.
 */
function AGENT_discoveryMarkdownLabel($value)
{
    $value = AGENT_discoveryText($value);
    return str_replace(array('\\', '[', ']'), array('\\\\', '\\[', '\\]'), $value);
}

/**
 * Human-readable provider label for public discovery output.
 */
function AGENT_discoveryProviderLabel($provider)
{
    $labels = array(
        'stories'     => 'Articles',
        'staticpages' => 'Static Pages'
    );

    return isset($labels[$provider]) ? $labels[$provider] : ucfirst((string) $provider);
}

/**
 * Build public llms-style discovery text for the active Geeklog site.
 */
function AGENT_buildLlmsText()
{
    global $_CONF;

    if (!AGENT_isEnabled() || (int) AGENT_getConfig('llms_enabled', 1) !== 1) {
        return '';
    }

    $siteName = isset($_CONF['site_name']) ? AGENT_discoveryText($_CONF['site_name']) : 'Geeklog site';
    $siteUrl = isset($_CONF['site_url']) ? rtrim((string) $_CONF['site_url'], '/') : '';
    $description = AGENT_discoveryText(AGENT_getConfig('site_description', ''));
    if ($description === '' && isset($_CONF['site_slogan'])) {
        $description = AGENT_discoveryText($_CONF['site_slogan']);
    }

    $limit = (int) AGENT_getConfig('recent_limit', 10);
    if ($limit < 1) {
        $limit = 10;
    }
    $limit = min($limit, 50);

    $lines = array();
    $lines[] = '# ' . $siteName;
    $lines[] = '';
    if ($description !== '') {
        $lines[] = '> ' . $description;
        $lines[] = '';
    }

    if ($siteUrl !== '') {
        $lines[] = 'Canonical site: ' . $siteUrl . '/';
        $lines[] = '';
    }

    $lines[] = '## Public content';
    $lines[] = '';

    $hasResources = false;
    foreach (AGENT_getEnabledProviders() as $provider) {
        if (!AGENT_providerAvailable($provider)) {
            continue;
        }

        $resources = AGENT_getProviderResources(
            $provider,
            array(
                'limit' => $limit,
                'order' => 'modified-desc'
            )
        );

        if (empty($resources)) {
            continue;
        }

        $hasResources = true;
        $lines[] = '### ' . AGENT_discoveryProviderLabel($provider);
        $lines[] = '';
        foreach ($resources as $resource) {
            if (empty($resource['title']) || empty($resource['canonical_url'])) {
                continue;
            }

            $title = AGENT_discoveryMarkdownLabel($resource['title']);
            $url = (string) $resource['canonical_url'];
            $excerpt = !empty($resource['excerpt']) ? AGENT_discoveryExcerpt($resource['excerpt']) : '';

            $line = '- [' . $title . '](' . $url . ')';
            if ($excerpt !== '') {
                $line .= ' — ' . $excerpt;
            }
            $lines[] = $line;
        }
        $lines[] = '';
    }

    if (!$hasResources) {
        $lines[] = 'No provider collection is currently available.';
        $lines[] = '';
    }

    if ($siteUrl !== '') {
        $lines[] = '## Site discovery';
        $lines[] = '';
        $lines[] = '- [Home](' . $siteUrl . '/)';
        $lines[] = '- [XML sitemap](' . $siteUrl . '/sitemap.xml)';
        $lines[] = '';
    }

    $lines[] = 'Generated by Geeklog Agent from the active site context and permission-aware provider contracts.';

    return implode("\n", $lines) . "\n";
}
