<?php

/**
 * Provider-neutral Markdown representation for Agent resources.
 *
 * @package Agent
 */

/**
 * Convert provider HTML/content to clean Markdown-friendly plain text while
 * preserving paragraph boundaries and removing unresolved Geeklog autotags.
 */
function AGENT_markdownContent($value)
{
    $value = (string) $value;
    $value = preg_replace('/<\s*br\s*\/?\s*>/iu', "\n", $value);
    $value = preg_replace('/<\s*\/\s*(p|div|h[1-6]|li|blockquote)\s*>/iu', "\n\n", $value);
    $value = html_entity_decode(strip_tags($value), ENT_QUOTES, 'UTF-8');
    $value = preg_replace('/\[[A-Za-z][A-Za-z0-9_-]*:[^\]\r\n]*\]/u', ' ', $value);
    $value = preg_replace('/\[image(?:\d+|X)\]/iu', ' ', $value);
    $value = str_replace("\r", '', $value);
    $lines = explode("\n", $value);
    foreach ($lines as $index => $line) {
        $lines[$index] = trim(preg_replace('/[\t ]+/u', ' ', $line));
    }
    $value = trim(implode("\n", $lines));
    $value = preg_replace('/\n{3,}/', "\n\n", $value);

    return trim($value);
}

/**
 * Normalize a timestamp/date value for a readable metadata line.
 */
function AGENT_markdownDate($value)
{
    if ($value === null || $value === '') {
        return '';
    }

    if (is_numeric($value)) {
        return gmdate('c', (int) $value);
    }

    return trim((string) $value);
}

/**
 * Build one public Markdown resource from the normalized Agent model.
 */
function AGENT_buildResourceMarkdown($provider, $id)
{
    if (!AGENT_isEnabled()) {
        return '';
    }

    $resource = AGENT_getProviderResource($provider, $id, 0);
    if (!is_array($resource) || empty($resource['title']) || empty($resource['canonical_url'])) {
        return '';
    }

    $title = AGENT_discoveryText($resource['title']);
    $excerpt = !empty($resource['excerpt']) ? AGENT_discoveryExcerpt($resource['excerpt'], 500) : '';
    $content = !empty($resource['content']) ? AGENT_markdownContent($resource['content']) : '';

    $lines = array();
    $lines[] = '# ' . $title;
    $lines[] = '';
    $lines[] = 'Canonical URL: ' . $resource['canonical_url'];
    $lines[] = 'Provider: ' . $resource['provider'];
    $lines[] = 'Type: ' . $resource['type'];

    if (!empty($resource['author'])) {
        $lines[] = 'Author: ' . AGENT_discoveryText($resource['author']);
    }
    if (!empty($resource['language'])) {
        $lines[] = 'Language: ' . AGENT_discoveryText($resource['language']);
    }

    $created = AGENT_markdownDate($resource['created']);
    if ($created !== '') {
        $lines[] = 'Created: ' . $created;
    }
    $modified = AGENT_markdownDate($resource['modified']);
    if ($modified !== '') {
        $lines[] = 'Modified: ' . $modified;
    }

    if ($excerpt !== '') {
        $lines[] = '';
        $lines[] = '## Summary';
        $lines[] = '';
        $lines[] = $excerpt;
    }

    if ($content !== '') {
        $lines[] = '';
        $lines[] = '## Content';
        $lines[] = '';
        $lines[] = $content;
    }

    $lines[] = '';
    $lines[] = '---';
    $lines[] = 'Generated by Geeklog Agent from the active site context and permission-aware provider contract.';

    return implode("\n", $lines) . "\n";
}
